### ISSUE TITLE
material 中的RefreshIndicator和依赖的pull_to_refresh中的RefreshIndicator冲突

### ISSUE THREAD

**Issue by memorycj** [hahafather007/flutter_weather#2]
lib/commom_import.dart:25:1: Error: 'RefreshIndicator' is exported from both 'package:flutter/src/material/refresh_indicator.dart' and 'package:pull_to_refresh/src/internals/indicator_wrap.dart'.
export 'package:pull_to_refresh/pull_to_refresh.dart';

**Comment by hahafather007** [comment]
直接把`pull_to_refresh: ^1.1.6`这个依赖删了，`Flutter packages get`一下，然后删除`common_import.dart`中的`export 'package:pull_to_refresh/pull_to_refresh.dart';`
这个库反正也没用到，之前忘了删了
