### ISSUE TITLE
main.dart问题

### ISSUE THREAD

**Issue by shuanglangdeliubei** [hahafather007/flutter_weather#3]
lib/main.dart:1: Warning: Interpreting this as package URI, 'package:flutter_weather/main.dart'.
file:///G:/SOFT/Flutter/flutter/packages/flutter/lib/src/rendering/box.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show lerpDouble;

**Comment by hahafather007** [comment]
你这是flutter环境没装好吧，报错显示你dart库里面都没有ui包
