### ISSUE TITLE
城市管理拖动城市  应用出错

### ISSUE THREAD

**Issue by Dboy233** [hahafather007/flutter_weather#6]
城市管理不能删除城市，拖动城市位置就报错了

**Comment by hahafather007** [comment]
你长按某个城市左滑或者右滑就可以删除。报错这个我这边复现不了呢，你能把错误发出来吗？

**Comment by Dboy233** [comment]
------------------
ぬひむヌヒム


 




------------------ 原始邮件 ------------------
发件人: "hahafather007"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 下午2:44
收件人: "hahafather007/flutter_weather"<flutter_weather@noreply.github.com>;
抄送: "哇啦啦。"<894230813@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hahafather007/flutter_weather] 城市管理拖动城市  应用出错 (#6)




你长按某个城市左滑或者右滑就可以删除。报错这个我这边复现不了呢，你能把错误发出来吗？
